[package]
name = "titan-tun"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
libloading = "0.8"
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
