[package]
name = "titan-system-proxy"
version.workspace = true
edition.workspace = true

[dependencies]
tracing = { workspace = true }
anyhow = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_Networking_WinInet"] }

[target.'cfg(target_os = "macos")'.dependencies]
